# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/VictorInfoDev/Atualizacoes-projeto/blob/main/Untitled11.ipynb
"""

#1
soma = 0
conta = 0
for i in range(5):
  num = int(input("Digite um número:"))
  if num < 0:
    print(num, "é negativo")
  else:
    soma = soma + num
    conta = conta + 1

print("Média de positivos:", soma/conta)

#2
for i in range(5):
  num = int(input("Digite um numero:"))
  if(num % 2 == 0):
    print("Par")
  if(num % 2 == 1):
    print("Impar")

#3
menor = 999999
maior = 0
num = 1
while(num != 0):
  num = int(input("Digite o numero:"))
  if(num != 0):
    if(menor > num):
      menor = num
    if(maior < num):
      maior = num
  else:
    menor = 0
    print("Menor:",menor)
    print("Maior:",maior)

#4
somapares = 0
somaimpar = 0
for i in range(5):
  num = int(input("Digite o valor:"))
  if(num >= 1 and num <= 100):
    if(num%2 == 1):
      somaimpar = somaimpar + num
    if(num%2 == 0):
      somapares = somapares + num
  else:
    print("*Digite numeros entre 1 e 100.")

print("Soma dos pares:",somapares)
print("Soma dos impares:",somaimpar)

#5
media = 0
for i in range(5):
  alt = float(input("Digite sua idade:"))
  media = media + alt

print("Média das idades é:",media/5)

#6
totalnegativos = 0
for i in range(10):
  num = int(input("Digite o valor:"))
  if(num < 0):
    totalnegativos = totalnegativos + 1
  
print("Total valores nagativos:",totalnegativos)

#7
totaltinta = float(input("Digite a quantidade de tinta da caneta em (ml):"))
qtdTinta = (totaltinta / 100) * 20
while(totaltinta != 0):
  print("Enquanto tem tinta a caneta escreve...")
  input("Escreva:")
  totaltinta = totaltinta - qtdTinta

if(totaltinta == 0):
  print("Acabou a tinta.")

#8
atletamaiorAlt = 0
atletamenorAlt = 99999999
atletamaiorIsc = 0
atletamenorIsc = 0
alturaAtleta = 0
for i in range(4):
  isc = int(input("Digite sua inscrição:"))
  alt = float(input("Digite sua altura:"))
  if(alt > atletamaiorAlt):
    atletamaiorAlt = alt
    atletamaiorIsc = isc
  if(alt < atletamenorAlt):
    atletamenorAlt = alt
    atletamenorIsc = isc
  alturaAtleta = alturaAtleta + alt

print("Maior atleta/ Altura:",atletamaiorAlt,"Inscrição:",atletamaiorIsc)
print("Menor atleta/ Altura:",atletamenorAlt,"Inscrição:",atletamenorIsc)
print("Media das alturas:",alturaAtleta/5)

